# Generated by Django 4.0.6 on 2023-05-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_oiimage_hdetail2_hiimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('Select_category_of_Receiving', models.CharField(max_length=20)),
            ],
        ),
    ]
