# Generated by Django 4.0.6 on 2023-05-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_select_category_of_receiving_recreq_scor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('scod', models.CharField(max_length=20)),
            ],
        ),
    ]
