# Generated by Django 4.0.6 on 2023-05-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_donreq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quick',
            old_name='qan',
            new_name='qaddress',
        ),
        migrations.RemoveField(
            model_name='quick',
            name='qage',
        ),
        migrations.RemoveField(
            model_name='quick',
            name='qbg',
        ),
        migrations.RemoveField(
            model_name='quick',
            name='qdob',
        ),
        migrations.RemoveField(
            model_name='quick',
            name='qge',
        ),
        migrations.RemoveField(
            model_name='quick',
            name='qheight',
        ),
        migrations.RemoveField(
            model_name='quick',
            name='qidtype',
        ),
        migrations.RemoveField(
            model_name='quick',
            name='qimage',
        ),
        migrations.RemoveField(
            model_name='quick',
            name='qtmr',
        ),
        migrations.RemoveField(
            model_name='quick',
            name='qweight',
        ),
        migrations.RemoveField(
            model_name='quick',
            name='username',
        ),
    ]
