# Generated by Django 4.0.6 on 2023-05-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_orgreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('request_for', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='orgreq',
            old_name='scod',
            new_name='request',
        ),
    ]
