# Generated by Django 4.0.6 on 2023-05-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rhosreq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rhosreq',
            old_name='rrequest_for',
            new_name='hosuserreq',
        ),
    ]
