# Generated by Django 4.0.6 on 2023-05-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_rrequest_for_rhosreq_hosuserreq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosreq',
            old_name='request_for',
            new_name='requesth',
        ),
    ]
