# Generated by Django 4.0.6 on 2023-05-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_request_for_hosreq_requesth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rdonreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('rec_req_to_donar', models.CharField(max_length=20)),
            ],
        ),
    ]
