# Generated by Django 4.0.6 on 2023-05-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rdonreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rorgreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('rec_req_to_organization', models.CharField(max_length=20)),
            ],
        ),
    ]
