# Generated by Django 4.0.6 on 2023-05-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_ohosreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hdonreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('org_req_to_hos', models.CharField(max_length=20)),
            ],
        ),
    ]
