# Generated by Django 4.0.6 on 2023-05-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_org_req_to_hos_hdonreq_hospital_req_to_don'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hrecreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('hsl_req_to_rec', models.CharField(max_length=20)),
            ],
        ),
    ]
