# Generated by Django 4.0.6 on 2023-06-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_horgreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreq',
            name='recusername',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
