# Generated by Django 4.0.6 on 2023-06-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_recreq_recusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgreq',
            name='orgusername',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
