# Generated by Django 4.0.6 on 2023-06-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_hosreq_hosusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='rorgreq',
            name='rorgusername',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
