# Generated by Django 4.0.6 on 2023-06-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_rorgreq_rorgusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhosreq',
            name='rhosusername',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
