# Generated by Django 4.0.6 on 2023-06-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_odonreq_odonusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='orecreq',
            name='orecusername',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
