# Generated by Django 4.0.6 on 2023-06-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_orecreq_orecusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohosreq',
            name='ohosusername',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
