# Generated by Django 4.0.6 on 2023-06-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_ohosreq_ohosusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdonreq',
            name='hdonusername',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
