# Generated by Django 4.0.6 on 2023-06-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_hdonreq_hdonusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrecreq',
            name='hrecusername',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
