# Generated by Django 4.2.2 on 2023-06-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_horgreq_horgusername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donreq',
        ),
        migrations.RenameField(
            model_name='orgreq',
            old_name='request',
            new_name='orequest',
        ),
    ]
